name:                ele
version:             0.1.0.0
github:              "praguevara/ele"
license:             BSD3
author:              praguevara
maintainer:          "praguevara@gmail.com"
copyright:           "2020 Pablo Ramón Guevara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/praguevara/ele#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- vector
- containers
- lens
- loop
- text
- optparse-applicative
- pretty-simple

library:
  source-dirs: src

executables:
  ele-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ele

tests:
  ele-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ele
